// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemIA.Models;

#nullable disable

namespace SistemIA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250819113925_Producto_AgregarDepositoPredeterminado")]
    partial class Producto_AgregarDepositoPredeterminado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemIA.Models.AsignacionHorario", b =>
                {
                    b.Property<int>("Id_Asignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Asignacion"));

                    b.Property<int?>("AsignadoPorId_Usuario")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Horario")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Asignacion");

                    b.HasIndex("Id_Horario");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("AsignacionesHorarios");
                });

            modelBuilder.Entity("SistemIA.Models.Asistencia", b =>
                {
                    b.Property<int>("Id_Asistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Asistencia"));

                    b.Property<bool>("AprobadaPorGerencia")
                        .HasColumnType("bit");

                    b.Property<int?>("AprobadoPorId_Usuario")
                        .HasColumnType("int")
                        .HasColumnName("AprobadoPorId_Usuario");

                    b.Property<int?>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<int?>("DiferenciaMinutos")
                        .HasColumnType("int");

                    b.Property<bool?>("EsDiaLaborable")
                        .HasColumnType("bit");

                    b.Property<bool>("EsRegistroAutomatico")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoJustificacion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EstadoPuntualidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinAusencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioAusencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraProgramada")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorasExtraMinutos")
                        .HasColumnType("int");

                    b.Property<int?>("Id_HorarioAplicado")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    b.Property<byte[]>("ImagenRegistro")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MetodoRegistro")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("MinutosToleranciAplicada")
                        .HasColumnType("int");

                    b.Property<string>("MotivoAusencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notas")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ObservacionesSistema")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("RequiereJustificacion")
                        .HasColumnType("bit");

                    b.Property<int>("Sucursal")
                        .HasColumnType("int");

                    b.Property<decimal?>("Temperatura")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("TextoJustificacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TiempoTrabajadoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UbicacionRegistro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Asistencia");

                    b.HasIndex("AprobadoPorId_Usuario");

                    b.HasIndex("Id_HorarioAplicado");

                    b.HasIndex("Id_Usuario");

                    b.HasIndex("Sucursal");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("SistemIA.Models.Ciudades", b =>
                {
                    b.Property<int>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCiudad"));

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCiudad");

                    b.ToTable("Ciudades", (string)null);
                });

            modelBuilder.Entity("SistemIA.Models.Clasificacion", b =>
                {
                    b.Property<int>("IdClasificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClasificacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdClasificacion");

                    b.ToTable("Clasificaciones");
                });

            modelBuilder.Entity("SistemIA.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoCliente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoDepartamento")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CodigoDistrito")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CodigoEstablecimiento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CompDireccion1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompDireccion2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DV")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionDepartamento")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("DescripcionDistrito")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EsExtranjero")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCiudad")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoContribuyente")
                        .HasColumnType("int");

                    b.Property<decimal?>("LimiteCredito")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("NaturalezaReceptor")
                        .HasColumnType("int");

                    b.Property<string>("NombreFantasia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumeroCasa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroDocumentoIdentidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PlazoDiasCredito")
                        .HasColumnType("int");

                    b.Property<bool>("PrecioDiferenciado")
                        .HasColumnType("bit");

                    b.Property<string>("RUC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Timbrado")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("TipoDocumentoIdentidadSifen")
                        .HasColumnType("int");

                    b.Property<string>("TipoOperacion")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("VencimientoTimbrado")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCliente");

                    b.HasIndex("CodigoPais");

                    b.HasIndex("IdCiudad");

                    b.HasIndex("IdTipoContribuyente");

                    b.HasIndex("TipoDocumento");

                    b.HasIndex("TipoOperacion");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemIA.Models.Deposito", b =>
                {
                    b.Property<int>("IdDeposito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDeposito"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("suc");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDeposito");

                    b.HasIndex("IdSucursal", "Nombre")
                        .IsUnique();

                    b.ToTable("Depositos", (string)null);
                });

            modelBuilder.Entity("SistemIA.Models.HorarioTrabajo", b =>
                {
                    b.Property<int>("Id_Horario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Horario"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Domingo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("FinBreak")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraEntrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<int>("Id_Sucursal")
                        .HasColumnType("int")
                        .HasColumnName("Id_Sucursal");

                    b.Property<TimeSpan?>("InicioBreak")
                        .HasColumnType("time");

                    b.Property<bool>("Jueves")
                        .HasColumnType("bit");

                    b.Property<bool>("Lunes")
                        .HasColumnType("bit");

                    b.Property<bool>("Martes")
                        .HasColumnType("bit");

                    b.Property<bool>("Miercoles")
                        .HasColumnType("bit");

                    b.Property<string>("NombreHorario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Sabado")
                        .HasColumnType("bit");

                    b.Property<bool>("Viernes")
                        .HasColumnType("bit");

                    b.HasKey("Id_Horario");

                    b.HasIndex("Id_Sucursal");

                    b.ToTable("HorariosTrabajo");
                });

            modelBuilder.Entity("SistemIA.Models.ListaPrecio", b =>
                {
                    b.Property<int>("IdListaPrecio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdListaPrecio"));

                    b.Property<bool>("AplicarDescuentoGlobal")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EsPredeterminada")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVigenciaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVigenciaHasta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMoneda")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdListaPrecio");

                    b.HasIndex("IdMoneda");

                    b.ToTable("ListasPrecios");
                });

            modelBuilder.Entity("SistemIA.Models.ListaPrecioDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<bool>("AplicarDescuento")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DescuentoEspecial")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdListaPrecio")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrecioAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdListaPrecio");

                    b.ToTable("ListasPreciosDetalles");
                });

            modelBuilder.Entity("SistemIA.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Marca");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Marca");

                    b.HasKey("IdMarca");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("SistemIA.Models.Moneda", b =>
                {
                    b.Property<int>("IdMoneda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMoneda"));

                    b.Property<string>("CodigoISO")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("EsMonedaBase")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMoneda");

                    b.ToTable("Monedas");
                });

            modelBuilder.Entity("SistemIA.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDeposito")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdDeposito");

                    b.HasIndex("IdProducto");

                    b.ToTable("MovimientosInventario", (string)null);
                });

            modelBuilder.Entity("SistemIA.Models.Paises", b =>
                {
                    b.Property<string>("CodigoPais")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodigoPais");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("SistemIA.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("CostoUnitarioGs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("IP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdClasificacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdDepositoPredeterminado")
                        .HasColumnType("int");

                    b.Property<int?>("IdMarca")
                        .HasColumnType("int");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("suc");

                    b.Property<int>("IdTipoIva")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitarioGs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PrecioUnitarioUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TipoItem")
                        .HasColumnType("int");

                    b.Property<string>("UndMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<string>("UnidadMedidaCodigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdClasificacion");

                    b.HasIndex("IdDepositoPredeterminado");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdTipoIva");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("SistemIA.Models.ProductoDeposito", b =>
                {
                    b.Property<int>("IdProductoDeposito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductoDeposito"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDeposito")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProductoDeposito");

                    b.HasIndex("IdDeposito");

                    b.HasIndex("IdProducto", "IdDeposito")
                        .IsUnique();

                    b.ToTable("ProductosDepositos", (string)null);
                });

            modelBuilder.Entity("SistemIA.Models.Proveedor", b =>
                {
                    b.Property<int>("Id_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Proveedor"));

                    b.Property<int?>("CodigoContribuyente")
                        .HasColumnType("int");

                    b.Property<string>("CodigoProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DV")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FotoLogo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("IdTipoContribuyente")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rubro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timbrado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VencimientoTimbrado")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Proveedor");

                    b.HasIndex("IdTipoContribuyente");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("SistemIA.Models.ProveedorSifenMejorado", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Celular")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CertificadoPassword")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CertificadoRuta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CodigoActividadEconomica")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<int>("CodigoCiudad")
                        .HasColumnType("int");

                    b.Property<string>("CodigoDepartamento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasDefaultValue("PRY")
                        .IsFixedLength();

                    b.Property<string>("CodigoProveedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DV")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionActividadEconomica")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DescripcionCiudad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DescripcionDepartamento")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Establecimiento")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaFacturacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoContribuyenteCatalogo")
                        .HasColumnType("int");

                    b.Property<decimal?>("LimiteCredito")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NombreFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroCasa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonaContacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PlazoPagoDias")
                        .HasColumnType("int");

                    b.Property<string>("PuntoExpedicion")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("RUC")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rubro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SaldoPendiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Timbrado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<int>("TipoContribuyente")
                        .HasColumnType("int");

                    b.Property<int>("TipoRegimen")
                        .HasColumnType("int");

                    b.Property<string>("UltimaSerie")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("UltimoNumeroDocumento")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("VencimientoTimbrado")
                        .HasColumnType("datetime2");

                    b.HasKey("IdProveedor");

                    b.HasIndex("IdTipoContribuyenteCatalogo");

                    b.ToTable("ProveedoresSifen", (string)null);
                });

            modelBuilder.Entity("SistemIA.Models.Rol", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Rol"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Rol");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("SistemIA.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ambiente")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Automatizado")
                        .HasColumnType("bit");

                    b.Property<bool>("CalculoAutomaticoHorasExtra")
                        .HasColumnType("bit");

                    b.Property<string>("CertificadoPassword")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CertificadoRuta")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Conexion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DV")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdCiudad")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("IpConsola")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<int>("MaximoHorasExtraDia")
                        .HasColumnType("int");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreSucursal")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumSucursal")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .IsFixedLength();

                    b.Property<string>("PuertoConsola")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PuntoExpedicion")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RUC")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<bool>("RequiereJustificacionSalidaTemprana")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiereJustificacionTardanza")
                        .HasColumnType("bit");

                    b.Property<string>("RubroEmpresa")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("SistemaPlaya")
                        .HasColumnType("bit");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Timbrado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ToleranciaEntradaMinutos")
                        .HasColumnType("int");

                    b.Property<int>("ToleranciaSalidaMinutos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCiudad");

                    b.ToTable("Sucursal", (string)null);
                });

            modelBuilder.Entity("SistemIA.Models.TipoCambio", b =>
                {
                    b.Property<int>("IdTipoCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoCambio"));

                    b.Property<bool>("EsAutomatico")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTipoCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fuente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdMonedaDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdMonedaOrigen")
                        .HasColumnType("int");

                    b.Property<decimal>("TasaCambio")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("TasaCompra")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoCambio");

                    b.HasIndex("IdMonedaDestino");

                    b.HasIndex("IdMonedaOrigen");

                    b.ToTable("TiposCambio");
                });

            modelBuilder.Entity("SistemIA.Models.TipoCambioHistorico", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fuente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdMonedaDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdMonedaOrigen")
                        .HasColumnType("int");

                    b.Property<decimal>("TasaCambio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TasaCompra")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdMonedaDestino");

                    b.HasIndex("IdMonedaOrigen");

                    b.ToTable("TiposCambioHistorico");
                });

            modelBuilder.Entity("SistemIA.Models.TipoOperacion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Comentario")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposOperacion");
                });

            modelBuilder.Entity("SistemIA.Models.TiposContribuyentes", b =>
                {
                    b.Property<int>("IdTipoContribuyente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoContribuyente"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoContribuyente");

                    b.ToTable("TiposContribuyentes");
                });

            modelBuilder.Entity("SistemIA.Models.TiposDocumentosIdentidad", b =>
                {
                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoDocumento");

                    b.ToTable("TiposDocumentosIdentidad");
                });

            modelBuilder.Entity("SistemIA.Models.TiposIva", b =>
                {
                    b.Property<int>("IdTipoIva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoIva"));

                    b.Property<string>("CodigoAbreviado")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CodigoSifen")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsPredeterminado")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TasaSifen")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoIva");

                    b.ToTable("TiposIva");
                });

            modelBuilder.Entity("SistemIA.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usu"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CI")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Comision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("EmbeddingFacial")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Estado_Usu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha_Ingreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("HuellaDigital")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal?>("IPS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Usu");

                    b.HasIndex("Id_Rol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemIA.Models.AsignacionHorario", b =>
                {
                    b.HasOne("SistemIA.Models.HorarioTrabajo", "HorarioTrabajo")
                        .WithMany("Asignaciones")
                        .HasForeignKey("Id_Horario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemIA.Models.Usuario", "Usuario")
                        .WithMany("Asignaciones")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HorarioTrabajo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemIA.Models.Asistencia", b =>
                {
                    b.HasOne("SistemIA.Models.Usuario", "AprobadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AprobadoPorId_Usuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemIA.Models.HorarioTrabajo", "HorarioAplicado")
                        .WithMany()
                        .HasForeignKey("Id_HorarioAplicado");

                    b.HasOne("SistemIA.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemIA.Models.Sucursal", "SucursalNavigation")
                        .WithMany()
                        .HasForeignKey("Sucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AprobadoPorUsuario");

                    b.Navigation("HorarioAplicado");

                    b.Navigation("SucursalNavigation");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemIA.Models.Cliente", b =>
                {
                    b.HasOne("SistemIA.Models.Paises", "Pais")
                        .WithMany("Clientes")
                        .HasForeignKey("CodigoPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemIA.Models.Ciudades", "Ciudad")
                        .WithMany("Clientes")
                        .HasForeignKey("IdCiudad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemIA.Models.TiposContribuyentes", "TipoContribuyente")
                        .WithMany("Clientes")
                        .HasForeignKey("IdTipoContribuyente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemIA.Models.TiposDocumentosIdentidad", "TipoDocumentoIdentidad")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemIA.Models.TipoOperacion", "TipoOperacionNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoOperacion");

                    b.Navigation("Ciudad");

                    b.Navigation("Pais");

                    b.Navigation("TipoContribuyente");

                    b.Navigation("TipoDocumentoIdentidad");

                    b.Navigation("TipoOperacionNavigation");
                });

            modelBuilder.Entity("SistemIA.Models.Deposito", b =>
                {
                    b.HasOne("SistemIA.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("SistemIA.Models.HorarioTrabajo", b =>
                {
                    b.HasOne("SistemIA.Models.Sucursal", "SucursalNavigation")
                        .WithMany()
                        .HasForeignKey("Id_Sucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SucursalNavigation");
                });

            modelBuilder.Entity("SistemIA.Models.ListaPrecio", b =>
                {
                    b.HasOne("SistemIA.Models.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("IdMoneda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Moneda");
                });

            modelBuilder.Entity("SistemIA.Models.ListaPrecioDetalle", b =>
                {
                    b.HasOne("SistemIA.Models.ListaPrecio", "ListaPrecio")
                        .WithMany("Detalles")
                        .HasForeignKey("IdListaPrecio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaPrecio");
                });

            modelBuilder.Entity("SistemIA.Models.MovimientoInventario", b =>
                {
                    b.HasOne("SistemIA.Models.Deposito", "Deposito")
                        .WithMany()
                        .HasForeignKey("IdDeposito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemIA.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Deposito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemIA.Models.Producto", b =>
                {
                    b.HasOne("SistemIA.Models.Clasificacion", "Clasificacion")
                        .WithMany()
                        .HasForeignKey("IdClasificacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemIA.Models.Deposito", "DepositoPredeterminado")
                        .WithMany()
                        .HasForeignKey("IdDepositoPredeterminado")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemIA.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SistemIA.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemIA.Models.TiposIva", "TipoIva")
                        .WithMany()
                        .HasForeignKey("IdTipoIva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clasificacion");

                    b.Navigation("DepositoPredeterminado");

                    b.Navigation("Marca");

                    b.Navigation("Sucursal");

                    b.Navigation("TipoIva");
                });

            modelBuilder.Entity("SistemIA.Models.ProductoDeposito", b =>
                {
                    b.HasOne("SistemIA.Models.Deposito", "Deposito")
                        .WithMany("Productos")
                        .HasForeignKey("IdDeposito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemIA.Models.Producto", "Producto")
                        .WithMany("StocksPorDeposito")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemIA.Models.Proveedor", b =>
                {
                    b.HasOne("SistemIA.Models.TiposContribuyentes", "TipoContribuyente")
                        .WithMany()
                        .HasForeignKey("IdTipoContribuyente");

                    b.Navigation("TipoContribuyente");
                });

            modelBuilder.Entity("SistemIA.Models.ProveedorSifenMejorado", b =>
                {
                    b.HasOne("SistemIA.Models.TiposContribuyentes", "TipoContribuyenteCatalogo")
                        .WithMany()
                        .HasForeignKey("IdTipoContribuyenteCatalogo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoContribuyenteCatalogo");
                });

            modelBuilder.Entity("SistemIA.Models.Sucursal", b =>
                {
                    b.HasOne("SistemIA.Models.Ciudades", "Ciudad")
                        .WithMany("Sucursales")
                        .HasForeignKey("IdCiudad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("SistemIA.Models.TipoCambio", b =>
                {
                    b.HasOne("SistemIA.Models.Moneda", "MonedaDestino")
                        .WithMany()
                        .HasForeignKey("IdMonedaDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemIA.Models.Moneda", "MonedaOrigen")
                        .WithMany()
                        .HasForeignKey("IdMonedaOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonedaDestino");

                    b.Navigation("MonedaOrigen");
                });

            modelBuilder.Entity("SistemIA.Models.TipoCambioHistorico", b =>
                {
                    b.HasOne("SistemIA.Models.Moneda", "MonedaDestino")
                        .WithMany()
                        .HasForeignKey("IdMonedaDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemIA.Models.Moneda", "MonedaOrigen")
                        .WithMany()
                        .HasForeignKey("IdMonedaOrigen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonedaDestino");

                    b.Navigation("MonedaOrigen");
                });

            modelBuilder.Entity("SistemIA.Models.Usuario", b =>
                {
                    b.HasOne("SistemIA.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemIA.Models.Ciudades", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("SistemIA.Models.Deposito", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SistemIA.Models.HorarioTrabajo", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("SistemIA.Models.ListaPrecio", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SistemIA.Models.Paises", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SistemIA.Models.Producto", b =>
                {
                    b.Navigation("StocksPorDeposito");
                });

            modelBuilder.Entity("SistemIA.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemIA.Models.TipoOperacion", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SistemIA.Models.TiposContribuyentes", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SistemIA.Models.TiposDocumentosIdentidad", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SistemIA.Models.Usuario", b =>
                {
                    b.Navigation("Asignaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
